LOAD DATA LOCAL INFILE 'F:/Ecommerce/shangchuan_data/user.csv'
INTO TABLE ods_user
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;